# Schema for the configuration files of the my_bo module.
action.configuration.term_push_front:
  type: action_configuration_default
  label: 'Push term in front'

action.configuration.term_unpush_front:
  type: action_configuration_default
  label: 'Unpush term from front'
